/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yasmeen.softwareproject;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.border.AbstractBorder;
class gh extends JPanel{
       @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        Color color1 = Color.BLACK.WHITE;
        Color color2 = Color.GREEN;
           GradientPaint gp = new GradientPaint(0, 0, color1, width, height, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
    
}


class but extends JButton{
    private Color color1;
    private Color color2;

    public but(String text, Color color1, Color color2) {
        super(text);
        this.color1 = color1;
        this.color2 = color2;
        setContentAreaFilled(false); // This is important to make sure we draw the background ourselves
    }

    @Override
    protected void paintComponent(Graphics g) {
        if (!isOpaque()) {
            int width = getWidth();
            int height = getHeight();
            Graphics2D g2d = (Graphics2D) g;
            GradientPaint gp = new GradientPaint(0, 0, color1, width, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
        super.paintComponent(g);
    }
}
/**
 *
 * @author Hp
 */
public class login extends JFrame {
public void removecontents(){
    jTextField1.setText("Enter Your Email Here");jTextField2.setText("");
    Application.loguppage.setVisible(false);
    login.this.setVisible(true);
    
}
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        jRadioButton1.setSelected(true);
        jTextField1.setBorder(new BottomBorder(Color.BLACK));
          jTextField2.setBorder(new BottomBorder(Color.BLACK));
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = screenSize.width / 2;
        int centerY = screenSize.height / 2;
        this.setLocation(centerX - this.getWidth() / 2, centerY - this.getHeight() / 2);
       
    }
static class BottomBorder extends AbstractBorder {
    private final Color color;

    public BottomBorder(Color color) {
        this.color = color;
    }

    @Override
    public void paintBorder(java.awt.Component c, Graphics g, int x, int y, int width, int height) {
        g.setColor(color);
        g.drawLine(x, height - 1, width, height - 1); // Draw bottom border
    }

    @Override
    public Insets getBorderInsets(java.awt.Component c) {
        return new Insets(0, 0, 1, 0); // Only bottom border
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        buttonGroup3 = new ButtonGroup();
        buttonGroup4 = new ButtonGroup();
        jPanel1 = new gh();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JPasswordField();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jRadioButton3 = new JRadioButton();
        jRadioButton4 = new JRadioButton();
        jButton2 = new but("LOGIN NOW",Color.GREEN, Color.WHITE);
        jButton1 = new but("LOGIN NOW",Color.GREEN, Color.WHITE);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(255, 255, 255));

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));

        jLabel1.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN NOW");

        jTextField1.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jTextField1.setText("Enter Your Email Here");
        jTextField1.setBorder(BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new Color(255, 255, 255));
        jRadioButton1.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jRadioButton1.setText("Owner");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new Color(255, 255, 255));
        jRadioButton2.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jRadioButton2.setText("Admin");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new Color(255, 255, 255));
        jRadioButton3.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jRadioButton3.setText("Supplier");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new Color(255, 255, 255));
        jRadioButton4.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jRadioButton4.setText("User");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jButton2.setForeground(new Color(255, 255, 255));
        jButton2.setText("LOGIN NOW");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setText("OR LOGUP NOW");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1)
                            .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
jRadioButton2.setSelected(false);
jRadioButton3.setSelected(false);
jRadioButton4.setSelected(false);
Application.type="Owner";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
jRadioButton2.setSelected(false);
jRadioButton1.setSelected(false);
jRadioButton3.setSelected(false);
Application.type="User";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
jRadioButton1.setSelected(false);
jRadioButton3.setSelected(false);
jRadioButton4.setSelected(false);

Application.type="Admin";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
jRadioButton2.setSelected(false);
jRadioButton4.setSelected(false);
jRadioButton1.setSelected(false);
Application.type="Supplier";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        
        jButton1.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
         jButton1.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 18));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 18));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Application.loguppage.setVisible(true);
        Application.loginpage.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
 if (isValidEmail(jTextField1.getText())) {
    boolean isValidUser = false;
    
    if (Application.type.equals("Owner")) {
        for (int i = 0; i < Application.Owners.size(); i++) {
            if (jTextField1.getText().equals(Application.Owners.get(i).getemail())) {
                if (jTextField2.getText().equals(Application.Owners.get(i).getpassword()+"")) {

                    Application.ownerpage.setVisible(true);
                    Application.publicuser=Application.Owners.get(i);
                    Application.ownerpage.jLabel2.setText("Welcome back " + Application.Owners.get(i).getname());
                    Application.ownerpage.jTextField1.setText(Application.Owners.get(i).getname());
                     Application.ownerpage.jTextField2.setText(Application.Owners.get(i).getphone()+"");
                      Application.ownerpage.jTextField3.setText(Application.Owners.get(i).getage()+"");
                      Application.ownerpage.jPasswordField1.setText("");
                    Application.loginpage.setVisible(false);
                    jTextField1.setText("");
                    jTextField2.setText("");
                  
                       String h="There is no messages to this account";
            for(int ip=0;ip<Application.publicuser.messages.size();ip++){
                if(ip==0) h="";
                h+=Application.publicuser.messages.get(ip)+"\n";
                    }

        
         Application.ownerpage.jTextArea2.setText(h);
         Application.ownerpage.jTextArea2.setEditable(false);
                    isValidUser = true;
                    break;
                } else {
                  
                    JOptionPane.showMessageDialog(null, "Please enter a valid password");
                    isValidUser = false;
                    break;
                }
            }
        }
    } else if (Application.type.equals("Admin")) {
        for (int i = 0; i < Application.Admins.size(); i++) {
            if (jTextField1.getText().equals(Application.Admins.get(i).getemail())) {
                if (jTextField2.getText().equals(Application.Admins.get(i).getpassword()+"")) {
                    Application.adminpage.jLabel2.setText("Welcome back " + Application.Admins.get(i).getname());
                    Application.adminpage.setVisible(true);
                    Application.loginpage.setVisible(false);
                    jTextField1.setText("");
                    jTextField2.setText("");
                    Application.publicuser=Application.Admins.get(i);
                    isValidUser = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a valid password");
                    isValidUser = false;
                    break;
                }
            }
        }
    } else if (Application.type.equals("Supplier")) {
        for (int i = 0; i < Application.suppliers.size(); i++) {
            if (jTextField1.getText().equals(Application.suppliers.get(i).getemail())) {
                if (jTextField2.getText().equals(Application.suppliers.get(i).getpassword()+"")) {
                    
                    Application.supplierspage.setVisible(true);
                    Application.loginpage.setVisible(false);
                    jTextField1.setText("");
                    Application.publicuser=Application.suppliers.get(i);
                    jTextField2.setText("");
                   Application.supplierspage.jTextField4.setText(Application.suppliers.get(i).getname());
                     Application.supplierspage.jTextField5.setText(Application.suppliers.get(i).getphone()+"");
                      Application.supplierspage.jTextField6.setText(Application.suppliers.get(i).getage()+"");
                      Application.supplierspage.jPasswordField12.setText("");
                    Application.supplierspage.jLabel2.setText("Welcome back " + Application.suppliers.get(i).getname());
                       String h="There is no messages to this account";
            for(int ip=0;ip<Application.publicuser.messages.size();ip++){
                if(ip==0) h="";
                h+=Application.publicuser.messages.get(ip)+"\n";
                    }
                 try{ JOptionPane.showMessageDialog(rootPane, h);}catch(Exception e){}
        
         Application.supplierspage.jTextArea2.setText(h);
         Application.supplierspage.jTextArea2.setEditable(false);
                    isValidUser = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a valid password");
                    isValidUser = false;
                    break;
                }
            }
        }
    } else {
        for (int i = 0; i < Application.users.size(); i++) {
            if (jTextField1.getText().equals(Application.users.get(i).getemail())) {
                if (jTextField2.getText().equals(Application.users.get(i).getpassword())) {
                    Application.ownerpage.setVisible(true);
                    Application.loginpage.setVisible(false);
                    jTextField1.setText("");
                    Application.publicuser=Application.users.get(i);
                    jTextField2.setText("");
                    isValidUser = true;
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a valid password");
                    isValidUser = false;
                    break;
                }
            }
        }
    }
    
    if (!isValidUser) {
        JOptionPane.showMessageDialog(null, "Email not found in our records");
    }
} else {
    JOptionPane.showMessageDialog(null, "Please enter a valid email");
}

     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    } public static boolean isValidEmail(String email) {
     String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        Pattern pattern = Pattern.compile(EMAIL_REGEX);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private ButtonGroup buttonGroup3;
    private ButtonGroup buttonGroup4;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton4;
    private JTextField jTextField1;
    private JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
