/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yasmeen.softwareproject;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

 
import javax.swing.*;
import java.awt.*;

class TransparentRadioButton extends JRadioButton {

    public TransparentRadioButton(String text) {
        super(text);
        // Ensure the button has a transparent background
        setOpaque(false);
        // Set the button's border to null to avoid any visible border
        setBorder(BorderFactory.createEmptyBorder());
        // Optionally, set the button's content area filled state to false
        setContentAreaFilled(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        // Set the background color to be fully transparent
        g.setColor(new Color(0, 0, 0, 0));
        g.fillRect(0, 0, getWidth(), getHeight());
        // Paint the radio button's content
        super.paintComponent(g);
    }

    @Override
    protected void paintBorder(Graphics g) {
        // Avoid painting the border
    }
}

public class Owner extends JFrame {
    ArrayList<String>m=new ArrayList<>();
   
    /**
     * Creates new form Owner
     */
    public Owner() {
        
        initComponents();
        jRadioButton1.setSelected(true);
//        jPanel8=new Application.ListDisplayPanel(m);
jTextArea2.setEditable(false);
if(Application.publicuser.messages.isEmpty()){
 jTextArea2.setText("There are no messages Received");
}else{
 jTextArea2.setText("");
 for(int i=0;i<Application.publicuser.messages.size();i++){
   jTextArea2.append(Application.publicuser.messages.get(i)+"\n");
 }
}
 ArrayList<String> items=new ArrayList<>();
       for(int i=0;i<Application.suppliers.size();i++){
          items.add(Application.suppliers.get(i).getname());
       }
    
Application.populateAndSetupList(jlist1, items);
if(!Application.suppliers.isEmpty()){
      jlist1.setEnabled(true);
    }  
 ArrayList<String> items2=new ArrayList<>();
       for(int i=0;i<Application.sales.size();i++){
          items2.add(Application.sales.get(i).getname()+"   "+Application.sales.get(i).status+"   "+Application.sales.get(i).getprofit());
       }
    
Application.populateAndSetupList(jlist3, items2);
if(!Application.sales.isEmpty()){
      jlist3.setEnabled(true);
    }  

  Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = screenSize.width / 2;
        int centerY = screenSize.height / 2;
        this.setLocation(centerX - this.getWidth() / 2, centerY - this.getHeight() / 2);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new ghk(Color.GREEN,Color.WHITE);
        jLabel2 = new JLabel();
        jTabbedPane11 = new JTabbedPane();
        jPanel3 = new ghk(Color.CYAN, Color.BLUE);
        jButton3 = new but1("Confirm", Color.green, Color.WHITE);
        jButton6 = new but1("Confirm", Color.green, Color.WHITE);
        jButton7 = new but1("Confirm", Color.green, Color.WHITE);
        jButton8 = new but1("Confirm", Color.green, Color.WHITE);
        jButton9 = new but1("Confirm", Color.green, Color.WHITE);
        jButton10 = new but1("Confirm", Color.green, Color.WHITE);
        jPanel4 = new ghk(Color.CYAN, Color.BLUE);
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel5 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jTextField3 = new JTextField();
        jLabel4 = new JLabel();
        jLabel6 = new JLabel();
        jPasswordField1 = new JPasswordField();
        jButton1 = new but1("Confirm", Color.green, Color.black);
        jPanel5 = new ghk(Color.CYAN, Color.BLUE);
        jLabel8 = new JLabel();
        jLabel10 = new JLabel();
        jButton2 = new but1("Confirm", Color.green, Color.black);
        jPanel1 = new JPanel();
        jLabel13 = new JLabel();
        jScrollPane5 = new JScrollPane();
        jlist3 = new JList<>();
        jRadioButton1 = new TransparentRadioButton("Complete");
        jRadioButton2 = new TransparentRadioButton("Pending");
        jRadioButton3 = new TransparentRadioButton("Cash");
        jPanel6 = new ghk(Color.CYAN, Color.BLUE);
        jLabel11 = new JLabel();
        jButton5 = new but1("Confirm", Color.green, Color.black);
        jLabel7 = new JLabel();
        jPasswordField2 = new JPasswordField();
        jLabel9 = new JLabel();
        jPasswordField3 = new JPasswordField();
        jPanel2 = new ghk(Color.BLUE,Color.CYAN);
        jPanel7 = new JPanel();
        jScrollPane2 = new JScrollPane();
        jTextArea2 = new JTextArea();
        jButton11 = new but1("Confirm", Color.green, Color.black);
        jPanel8 = new JPanel();
        jLabel12 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jScrollPane3 = new JScrollPane();
        jlist1 = new JList<>();
        jButton4 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("Welcome Back Yasmeen");

        jButton3.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton3.setForeground(new Color(255, 255, 255));
        jButton3.setText("Add Product");
        jButton3.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton6.setForeground(new Color(255, 255, 255));
        jButton6.setText("Update Product");
        jButton6.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton7.setForeground(new Color(255, 255, 255));
        jButton7.setText("Monitor sales and profits");
        jButton7.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton8.setForeground(new Color(255, 255, 255));
        jButton8.setText("Remove Product");
        jButton8.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton9.setForeground(new Color(255, 255, 255));
        jButton9.setText("Implement discount");
        jButton9.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton10.setForeground(new Color(255, 255, 255));
        jButton10.setText("best-selling product");
        jButton10.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jButton8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Product Management", jPanel3);

        jLabel1.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel1.setText("Change the Phone Number");

        jLabel3.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel3.setText("Change the Name ");

        jLabel5.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel5.setText("Change the Age");

        jTextField1.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new Font("Stylus BT", 0, 24)); // NOI18N

        jLabel6.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel6.setText("Confirm the password");

        jPasswordField1.setFont(new Font("Segoe UI", 0, 18)); // NOI18N

        jButton1.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setText("Confirm");
        jButton1.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordField1)
                    .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3, GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                        .addComponent(jLabel6)))
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 317, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(24, 24, 24))
        );

        jTabbedPane11.addTab("Account Management ", jPanel4);

        jLabel8.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel8.setText("Change the Status ");

        jButton2.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton2.setForeground(new Color(255, 255, 255));
        jButton2.setText("Confirm");
        jButton2.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jLabel13.setText("Choose an Order");

        jScrollPane5.setViewportView(jlist3);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel13)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5))
        );

        jRadioButton1.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new Color(255, 255, 255));
        jRadioButton1.setText("Complete");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new Color(255, 255, 255));
        jRadioButton2.setText("Pending");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new Color(255, 255, 255));
        jRadioButton3.setText("Cash");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(54, 54, 54)))
                .addGap(8, 8, 8))
        );

        jTabbedPane11.addTab("Order Management ", jPanel5);

        jButton5.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton5.setForeground(new Color(255, 255, 255));
        jButton5.setText("Confirm Changing password");
        jButton5.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel7.setText("Enter the old Password");

        jPasswordField2.setFont(new Font("Stylus BT", 0, 24)); // NOI18N

        jLabel9.setFont(new Font("Stylus BT", 0, 24)); // NOI18N
        jLabel9.setText("Enter the new Password");

        jPasswordField3.setFont(new Font("Stylus BT", 0, 24)); // NOI18N

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField2)
                    .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jPasswordField3))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jTabbedPane11.addTab("Change Password", jPanel6);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jButton11.setFont(new Font("Stylus BT", 1, 24)); // NOI18N
        jButton11.setForeground(new Color(255, 255, 255));
        jButton11.setText("Confirm");
        jButton11.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new Font("Stylus BT", 0, 18)); // NOI18N
        jLabel12.setText("Choose a Supplier");

        GroupLayout jPanel8Layout = new GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel12)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter the message here");
        jScrollPane1.setViewportView(jTextArea1);

        jlist1.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                jlist1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jlist1);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jTabbedPane11.addTab("Suppliers", jPanel2);

        jButton4.setText("Log-out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        GroupLayout jPanel13Layout = new GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane11)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane11, GroupLayout.PREFERRED_SIZE, 374, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Application.ownerpage.setVisible(false);
             Application.ownerpage=new Owner();
        Application.loginpage.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         Application.status="Pending";
         jRadioButton3.setSelected(false);
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(true);
         
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!Application.isNumber(jTextField3.getText())||jTextField3.getText().length()>=3){
            JOptionPane.showMessageDialog(rootPane, "Enter a valid age");}
        //        else if(jTextField2.getText().length()!=10||Application.isNumber(jTextField2.getText())){
            //         JOptionPane.showMessageDialog(rootPane, "Enter a valid Phone Number");}
        else {
            Application.updateinformation(jTextField1.getText(), Integer.parseInt(jTextField3.getText()), Integer.parseInt(jTextField2.getText()), Integer.parseInt(jPasswordField1.getText()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton10MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        // TODO add your handling code here:
        jButton10.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton10MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        // TODO add your handling code here:
        jButton10.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          String index=JOptionPane.showInputDialog(Application.getallproducts());
        if(Application.isNumber(index)){
            int x=Integer.parseInt(index);
            if(x<0||x>Application.products.size()){
                JOptionPane.showMessageDialog(rootPane, "Enter a valid value");
            }else{
             String discount=JOptionPane.showInputDialog("How much is the new Discount for the Product ?");
                if(discount.isEmpty()){
                  Application.implementdiscount(0, Application.products.get(x-1));
//                     JOptionPane.showMessageDialog(rootPane, "The product "+name+" is added with discount 0");
                  }else{
                         if(Application.isNumber(discount)){
                         int dis=Integer.parseInt(discount);
                         if(dis<0||dis>=100){
                             JOptionPane.showMessageDialog(rootPane, "The Discount is not correct");
                         }else{
                        Application.implementdiscount(dis, Application.products.get(x-1));
//                          JOptionPane.showMessageDialog(rootPane, "The product "+name+" is added with discount "+Integer.parseInt(discount));
                         }
                     }else{
                          JOptionPane.showMessageDialog(rootPane, "The Discount value is not valid");   
                         }
                  }
             
            }
        }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid value");
              }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
        jButton9.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        // TODO add your handling code here:
        jButton9.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton8MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jButton8.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton8MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jButton8.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton7MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        jButton7.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
        jButton7.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton6MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jButton6.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton3MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 24));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setFont(new Font(jButton1.getFont().getFontName(), jButton1.getFont().getStyle(), 30));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String index=JOptionPane.showInputDialog(Application.getallproducts());
        if(Application.isNumber(index)){
            int x=Integer.parseInt(index);
            if(x<0||x>Application.products.size()){
                JOptionPane.showMessageDialog(rootPane, "Enter a valid value");
            }else{
              String str1=JOptionPane.showInputDialog("What is the new Price of the product ?");   
              if(Application.isNumber(str1)){
                  String str2=JOptionPane.showInputDialog("What is the new Expire Date of the product ?"); 
                  if(Application.isValidFutureDate(str2)){
                      Application.updateproduct(x-1, Integer.parseInt(str1), str2);
                  }else{
                      JOptionPane.showMessageDialog(rootPane, "Enter a valid Expire Date");
                  }
              }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid Price");
              }
            }
        }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid value");
              }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name,price,quantity,date,discount;
        boolean flag=true;
        name=JOptionPane.showInputDialog("What is the name of the new product ?");
        for(int i=0;i<Application.products.size();i++){
         if(name.equals(Application.products.get(i))){
             flag=false;
             JOptionPane.showMessageDialog(rootPane, "The Prpduct is exist , If you want more of it please request it from a Supplier");
             break;
             
         }   
        }
        if(flag){
            price=JOptionPane.showInputDialog("What is the price of the new product ?");
            if(Application.isNumber(price)){
              quantity=JOptionPane.showInputDialog("What is the quantity of the new product ?");  
              if(Application.isNumber(quantity)){
                  date=JOptionPane.showInputDialog("What is the Expire Date of the new product ? \nexample : 1/1/2024"); 
                  if(Application.isValidFutureDate(date)){
                     discount=JOptionPane.showInputDialog("How much is the discount of the new product ?"); 
                  if(discount.isEmpty()){
                     Application.addproduct(name, Integer.parseInt(price), Integer.parseInt(quantity), date, 0);
//                     JOptionPane.showMessageDialog(rootPane, "The product "+name+" is added with discount 0");
                  }else{
                         if(Application.isNumber(discount)){
                         int dis=Integer.parseInt(discount);
                         if(dis<0||dis>=100){
                             JOptionPane.showMessageDialog(rootPane, "The Discount is not correct");
                         }else{
                          Application.addproduct(name, Integer.parseInt(price), Integer.parseInt(quantity), date, Integer.parseInt(discount));  
//                          JOptionPane.showMessageDialog(rootPane, "The product "+name+" is added with discount "+Integer.parseInt(discount));
                         }
                     }
                  }
                  }else{
                      JOptionPane.showMessageDialog(rootPane, "Enter a valid Expire Date");
                  }
              }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid Quantity");
              }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter a valid Price");
            }
            
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          String index=JOptionPane.showInputDialog(Application.getallproducts());
        if(Application.isNumber(index)){
            int x=Integer.parseInt(index);
            if(x<0||x>Application.products.size()){
                JOptionPane.showMessageDialog(rootPane, "Enter a valid value");
            }else{
              Application.removeproduct(Application.products.get(x-1).getname());
            }
        }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid value");
              }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,Application.getsalesmessage());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "The Best Salling profit came from the Product : "+Application.getmaxprofit().getname().toUpperCase()+" with Profit : "+Application.maxindex);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
        if(jPasswordField2.getText().length()<8||jPasswordField3.getText().length()<8){
            JOptionPane.showMessageDialog(rootPane, "Enter a valid password length");
        }else{
            if(Application.isNumber(jPasswordField2.getText())){
              if(Application.isNumber(jPasswordField3.getText())){
                if(jPasswordField2.getText().equals(Application.publicuser.getpassword()+"")){
                  Application.updatepassword(Integer.parseInt(jPasswordField3.getText()));
                }else{
                      JOptionPane.showMessageDialog(rootPane, "The Old password is not correct");
                }
            }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid new password ");
            }  
            }else{
                  JOptionPane.showMessageDialog(rootPane, "Enter a valid old password ");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11MouseExited(MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseExited

    private void jlist1ValueChanged(ListSelectionEvent evt) {//GEN-FIRST:event_jlist1ValueChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jlist1ValueChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
       if(Application.suppliers.isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "There are no suppliers to send messages");
       }else{
           for(int i=0;i<Application.suppliers.size();i++){
           if(Application.suppliers.get(i).getname().equals(Application.suppliername)){
              Application.suppliers.get(i).messages.add("From "+Application.publicuser.getname()+" : "+jTextArea1.getText());
              JOptionPane.showMessageDialog(rootPane, "The message is sent to the supplier "+Application.suppliername);
              jTextArea1.setText("");
             break;
           }
       } 
       }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        Application.status="Complete";
        jRadioButton3.setSelected(false);
jRadioButton2.setSelected(false);
jRadioButton1.setSelected(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here
jRadioButton2.setSelected(false);
jRadioButton1.setSelected(false);
jRadioButton3.setSelected(true);
         Application.status="Cash";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(Application.sales.isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "There are no Orders happened");
        }else{
            Application.sales.get(Application.order).updatestatus(Application.status);
             ArrayList<String> items2=new ArrayList<>();
       for(int i=0;i<Application.sales.size();i++){
          items2.add(Application.sales.get(i).getname()+"   "+Application.sales.get(i).status+"   "+Application.sales.get(i).getprofit());
       }
   
Application.populateAndSetupList(jlist3, items2);
if(!Application.sales.isEmpty()){
      jlist3.setEnabled(true);
    }  

        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
class but1 extends JButton{
    private Color color1;
    private Color color2;

    public but1(String text, Color color1, Color color2) {
        super(text);
        this.color1 = color1;
        this.color2 = color2;
        setContentAreaFilled(false); // This is important to make sure we draw the background ourselves
    }

    @Override
    protected void paintComponent(Graphics g) {
        if (!isOpaque()) {
            int width = getWidth();
            int height = getHeight();
            Graphics2D g2d = (Graphics2D) g;
            GradientPaint gp = new GradientPaint(0, 0, color1, width, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
        super.paintComponent(g);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton9;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    public JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel13;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    public JPasswordField jPasswordField1;
    private JPasswordField jPasswordField2;
    private JPasswordField jPasswordField3;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton3;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane5;
    private JTabbedPane jTabbedPane11;
    private JTextArea jTextArea1;
    public JTextArea jTextArea2;
    public JTextField jTextField1;
    public JTextField jTextField2;
    public JTextField jTextField3;
    private JList<String> jlist1;
    private JList<String> jlist3;
    // End of variables declaration//GEN-END:variables
}
